# Site settings
title: 大蔚陈
description: "专注于产品与用户体验设计。Framer.js, Quartz Composer"
baseurl: ""
url: "www.idavidchen.com"

# Build settings
markdown: kramdown
paginate: 5
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is
paginate_path: "page/:num"
highlighter: pygments

colors:  #in hex code if not noted else
  primary: "#00b3fe" 
  primary_rgb: "0, 179, 254" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

sass:
  style: compressed